require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
  StyleGuideBaseURL: https://rubystyle.guide
  DocumentationBaseURL: https://docs.rubocop.org/rubocop
  ActiveSupportExtensionsEnabled: true

Metrics/BlockLength:
  Max: 200

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails:
  Enabled: true
