name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Run Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop --parallel

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - '5432:5432'
        options: >-
          --health-cmd="pg_isready -U rails"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up database schema
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/rails_test
        run: |
          bin/rails db:drop db:create
          PGPASSWORD=password psql -h localhost -U postgres -d rails_test -c 'CREATE EXTENSION IF NOT EXISTS "pgcrypto";'
          bin/rails db:migrate

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/rails_test
        run: bin/bundle exec rspec
